-- This file has been generated by Ion. Do not edit.
return {
    [0] = {
        ["type"] = "WRootWin",
        ["name"] = "WRootWin",
        ["managed"] = {
            [1] = {
                ["type"] = "WGroupWS",
                ["name"] = "WGroupWS",
                ["hidden"] = true,
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1366,
                    ["h"] = 768,
                },
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["name"] = "WTiling",
                        ["bottom"] = true,
                        ["level"] = 0,
                        ["sizepolicy"] = "full",
                        ["geom"] = {
                            ["y"] = 0,
                            ["x"] = 0,
                            ["w"] = 1366,
                            ["h"] = 768,
                        },
                        ["split_tree"] = {
                            ["tls"] = 753,
                            ["tl"] = {
                                ["tls"] = 414,
                                ["tl"] = {
                                    ["tls"] = 377,
                                    ["tl"] = {
                                        ["regparams"] = {
                                            ["mode"] = 1,
                                            ["type"] = "WFrame",
                                            ["name"] = "WFrame",
                                            ["managed"] = {
                                            },
                                        },
                                        ["type"] = "WSplitRegion",
                                    },
                                    ["dir"] = "vertical",
                                    ["brs"] = 376,
                                    ["br"] = {
                                        ["regparams"] = {
                                            ["mode"] = 1,
                                            ["type"] = "WFrame",
                                            ["name"] = "WFrame<4>",
                                            ["managed"] = {
                                            },
                                        },
                                        ["type"] = "WSplitRegion",
                                    },
                                    ["type"] = "WSplitSplit",
                                },
                                ["dir"] = "horizontal",
                                ["brs"] = 952,
                                ["br"] = {
                                    ["regparams"] = {
                                        ["mode"] = 1,
                                        ["type"] = "WFrame",
                                        ["name"] = "WFrame<1>",
                                        ["managed"] = {
                                        },
                                    },
                                    ["type"] = "WSplitRegion",
                                },
                                ["type"] = "WSplitSplit",
                            },
                            ["dir"] = "vertical",
                            ["brs"] = 15,
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["type"] = "WSplitSplit",
                        },
                    },
                },
                ["level"] = 0,
            },
            [2] = {
                ["type"] = "WGroupWS",
                ["name"] = "WGroupWS<1>",
                ["hidden"] = true,
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1366,
                    ["h"] = 768,
                },
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["name"] = "WTiling<1>",
                        ["bottom"] = true,
                        ["level"] = 0,
                        ["sizepolicy"] = "full",
                        ["geom"] = {
                            ["y"] = 0,
                            ["x"] = 0,
                            ["w"] = 1366,
                            ["h"] = 768,
                        },
                        ["split_tree"] = {
                            ["tls"] = 678,
                            ["tl"] = {
                                ["regparams"] = {
                                    ["mode"] = 1,
                                    ["type"] = "WFrame",
                                    ["name"] = "WFrame<3>",
                                    ["managed"] = {
                                    },
                                },
                                ["type"] = "WSplitRegion",
                            },
                            ["dir"] = "horizontal",
                            ["brs"] = 688,
                            ["br"] = {
                                ["regparams"] = {
                                    ["mode"] = 1,
                                    ["type"] = "WFrame",
                                    ["name"] = "WFrame<2>",
                                    ["managed"] = {
                                    },
                                },
                                ["type"] = "WSplitRegion",
                            },
                            ["type"] = "WSplitSplit",
                        },
                    },
                },
                ["level"] = 0,
            },
            [3] = {
                ["type"] = "WGroupWS",
                ["name"] = "WGroupWS<2>",
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1366,
                    ["h"] = 768,
                },
                ["switchto"] = true,
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["name"] = "WTiling<2>",
                        ["bottom"] = true,
                        ["level"] = 0,
                        ["sizepolicy"] = "full",
                        ["geom"] = {
                            ["y"] = 0,
                            ["x"] = 0,
                            ["w"] = 1366,
                            ["h"] = 768,
                        },
                        ["split_tree"] = {
                            ["tls"] = 753,
                            ["tl"] = {
                                ["tls"] = 563,
                                ["tl"] = {
                                    ["regparams"] = {
                                        ["mode"] = 1,
                                        ["type"] = "WFrame",
                                        ["name"] = "WFrame<7>",
                                        ["managed"] = {
                                            [1] = {
                                                ["type"] = "WGroupCW",
                                                ["name"] = "WGroupCW",
                                                ["geom"] = {
                                                    ["y"] = 19,
                                                    ["x"] = 1,
                                                    ["w"] = 561,
                                                    ["h"] = 733,
                                                },
                                                ["switchto"] = true,
                                                ["sizepolicy"] = "full",
                                                ["managed"] = {
                                                    [1] = {
                                                        ["type"] = "WClientWin",
                                                        ["bottom"] = true,
                                                        ["windowid"] = 12582953,
                                                        ["checkcode"] = 1,
                                                        ["sizepolicy"] = "full",
                                                        ["geom"] = {
                                                            ["y"] = 0,
                                                            ["x"] = 0,
                                                            ["w"] = 561,
                                                            ["h"] = 733,
                                                        },
                                                        ["level"] = 1,
                                                    },
                                                },
                                                ["level"] = 0,
                                            },
                                        },
                                    },
                                    ["type"] = "WSplitRegion",
                                },
                                ["dir"] = "horizontal",
                                ["brs"] = 803,
                                ["br"] = {
                                    ["regparams"] = {
                                        ["mode"] = 1,
                                        ["type"] = "WFrame",
                                        ["name"] = "WFrame<6>",
                                        ["managed"] = {
                                            [1] = {
                                                ["type"] = "WGroupCW",
                                                ["name"] = "WGroupCW<1>",
                                                ["geom"] = {
                                                    ["y"] = 19,
                                                    ["x"] = 1,
                                                    ["w"] = 801,
                                                    ["h"] = 733,
                                                },
                                                ["switchto"] = true,
                                                ["sizepolicy"] = "full",
                                                ["managed"] = {
                                                    [1] = {
                                                        ["type"] = "WClientWin",
                                                        ["bottom"] = true,
                                                        ["windowid"] = 12583030,
                                                        ["checkcode"] = 2,
                                                        ["sizepolicy"] = "full",
                                                        ["geom"] = {
                                                            ["y"] = 0,
                                                            ["x"] = 0,
                                                            ["w"] = 801,
                                                            ["h"] = 733,
                                                        },
                                                        ["level"] = 1,
                                                    },
                                                },
                                                ["level"] = 0,
                                            },
                                        },
                                    },
                                    ["type"] = "WSplitRegion",
                                },
                                ["type"] = "WSplitSplit",
                            },
                            ["dir"] = "vertical",
                            ["brs"] = 15,
                            ["br"] = {
                                ["type"] = "WSplitST",
                            },
                            ["type"] = "WSplitSplit",
                        },
                    },
                },
                ["level"] = 0,
            },
            [4] = {
                ["type"] = "WGroupWS",
                ["name"] = "WGroupWS<3>",
                ["hidden"] = true,
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1366,
                    ["h"] = 768,
                },
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["type"] = "WTiling",
                        ["name"] = "WTiling<3>",
                        ["bottom"] = true,
                        ["level"] = 0,
                        ["sizepolicy"] = "full",
                        ["geom"] = {
                            ["y"] = 0,
                            ["x"] = 0,
                            ["w"] = 1366,
                            ["h"] = 768,
                        },
                        ["split_tree"] = {
                            ["tls"] = 411,
                            ["tl"] = {
                                ["tls"] = 375,
                                ["tl"] = {
                                    ["regparams"] = {
                                        ["mode"] = 1,
                                        ["type"] = "WFrame",
                                        ["name"] = "WFrame<9>",
                                        ["managed"] = {
                                        },
                                    },
                                    ["type"] = "WSplitRegion",
                                },
                                ["dir"] = "vertical",
                                ["brs"] = 393,
                                ["br"] = {
                                    ["regparams"] = {
                                        ["mode"] = 1,
                                        ["type"] = "WFrame",
                                        ["name"] = "WFrame<11>",
                                        ["managed"] = {
                                        },
                                    },
                                    ["type"] = "WSplitRegion",
                                },
                                ["type"] = "WSplitSplit",
                            },
                            ["dir"] = "horizontal",
                            ["brs"] = 955,
                            ["br"] = {
                                ["regparams"] = {
                                    ["mode"] = 1,
                                    ["type"] = "WFrame",
                                    ["name"] = "WFrame<10>",
                                    ["managed"] = {
                                    },
                                },
                                ["type"] = "WSplitRegion",
                            },
                            ["type"] = "WSplitSplit",
                        },
                    },
                },
                ["level"] = 0,
            },
            [5] = {
                ["type"] = "WGroupWS",
                ["sizepolicy"] = "full",
                ["managed"] = {
                    [1] = {
                        ["geom"] = {
                            ["y"] = 21,
                            ["x"] = 34,
                            ["w"] = 1300,
                            ["h"] = 728,
                        },
                        ["type"] = "WFrame",
                        ["name"] = "*scratchpad*",
                        ["bottom"] = true,
                        ["level"] = 1025,
                        ["mode"] = 0,
                        ["managed"] = {
                            [1] = {
                                ["type"] = "WGroupCW",
                                ["name"] = "WGroupCW<2>",
                                ["geom"] = {
                                    ["y"] = 19,
                                    ["x"] = 1,
                                    ["w"] = 1298,
                                    ["h"] = 707,
                                },
                                ["switchto"] = true,
                                ["sizepolicy"] = "full",
                                ["managed"] = {
                                    [1] = {
                                        ["type"] = "WClientWin",
                                        ["bottom"] = true,
                                        ["windowid"] = 14680452,
                                        ["checkcode"] = 3,
                                        ["sizepolicy"] = "full",
                                        ["geom"] = {
                                            ["y"] = 0,
                                            ["x"] = 0,
                                            ["w"] = 1298,
                                            ["h"] = 707,
                                        },
                                        ["level"] = 1,
                                    },
                                },
                                ["level"] = 0,
                            },
                        },
                        ["sizepolicy"] = "free_glue",
                    },
                },
                ["unnumbered"] = true,
                ["name"] = "*scratchws*",
                ["pseudomodal"] = true,
                ["level"] = 1,
                ["geom"] = {
                    ["y"] = 0,
                    ["x"] = 0,
                    ["w"] = 1366,
                    ["h"] = 768,
                },
                ["hidden"] = true,
            },
        },
    },
}

